// @ts-nocheck -- skip type checking
import * as docs_7 from "../content/docs/reference/cli-commands.mdx?collection=docs&hash=1774136792211"
import * as docs_6 from "../content/docs/modules/universal-transcript.mdx?collection=docs&hash=1774136792211"
import * as docs_5 from "../content/docs/modules/mcp-channel.mdx?collection=docs&hash=1774136792211"
import * as docs_4 from "../content/docs/modules/harness-system.mdx?collection=docs&hash=1774136792211"
import * as docs_3 from "../content/docs/guide/headless-shard-integration.mdx?collection=docs&hash=1774136792211"
import * as docs_2 from "../content/docs/concepts/introduction.mdx?collection=docs&hash=1774136792211"
import * as docs_1 from "../content/docs/concepts/architecture.mdx?collection=docs&hash=1774136792211"
import * as docs_0 from "../content/docs/index.mdx?collection=docs&hash=1774136792211"
import { _runtime } from "fumadocs-mdx/runtime/next"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"index.mdx","fullPath":"content/docs/index.mdx"}, data: docs_0 }, { info: {"path":"concepts/architecture.mdx","fullPath":"content/docs/concepts/architecture.mdx"}, data: docs_1 }, { info: {"path":"concepts/introduction.mdx","fullPath":"content/docs/concepts/introduction.mdx"}, data: docs_2 }, { info: {"path":"guide/headless-shard-integration.mdx","fullPath":"content/docs/guide/headless-shard-integration.mdx"}, data: docs_3 }, { info: {"path":"modules/harness-system.mdx","fullPath":"content/docs/modules/harness-system.mdx"}, data: docs_4 }, { info: {"path":"modules/mcp-channel.mdx","fullPath":"content/docs/modules/mcp-channel.mdx"}, data: docs_5 }, { info: {"path":"modules/universal-transcript.mdx","fullPath":"content/docs/modules/universal-transcript.mdx"}, data: docs_6 }, { info: {"path":"reference/cli-commands.mdx","fullPath":"content/docs/reference/cli-commands.mdx"}, data: docs_7 }], [{"info":{"path":"meta.json","fullPath":"content/docs/meta.json"},"data":{"title":"Orbh","pages":["index","concepts","modules","guide","reference"]}}, {"info":{"path":"guide/meta.json","fullPath":"content/docs/guide/meta.json"},"data":{"title":"Guides","pages":["headless-shard-integration"]}}, {"info":{"path":"concepts/meta.json","fullPath":"content/docs/concepts/meta.json"},"data":{"title":"Concepts","pages":["introduction","architecture"]}}, {"info":{"path":"modules/meta.json","fullPath":"content/docs/modules/meta.json"},"data":{"title":"Modules","pages":["universal-transcript","harness-system","mcp-channel"]}}, {"info":{"path":"reference/meta.json","fullPath":"content/docs/reference/meta.json"},"data":{"title":"Reference","pages":["cli-commands"]}}])